version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: cron
      cronjob: 0 6 * * *
      timezone: America/Los_Angeles
    groups:
      go-minor-patch:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
    reviewers:
      - agoodkind
